### ISSUE TITLE
language request needs to be 'GET' in APIS.py 

### ISSUE THREAD

**Issue by Isaha-Miller** [argosopentech/argos-translate#449]
urllib is throwing a `urllib.error.HTTPError: HTTP Error 405: METHOD NOT ALLOWED` error because languages() is not specifying a `GET` request. The fix is to change line 82 `req = request.Request(url, data=url_params.encode())` to an explicit `GET`.

```python
def languages(self):
        """Retrieve list of supported languages.

        Returns: A list of available languages ex. [{"code":"en", "name":"English"}]
        """

        url = self.url + "languages"

        params = dict()

        if self.api_key is not None:
            params["api_key"] = self.api_key

        url_params = parse.urlencode(params)

        req = request.Request(url, data=url_params.encode(),method="GET")

        response = request.urlopen(req)

        response_str = response.read().decode()

        return json.loads(response_str)```

**Comment by PJ-Finlay** [comment]
I think the LibreTranslate API changed slightly. We had this issue with the Python API too. It's fixed in the Python API so maybe we can just copy code from there. If someone makes a pull request for this I'll merge it.

**Comment by Bryandero98** [comment]
Hi! I'd like to fix this — I use argostranslate as the translation engine in a project of mine. Confirmed the bug still reproduces on current main, and confirmed libretranslatepy already has the fix (just adding `method="GET"` to the `languages()` request, exactly as suggested in this issue). Could you assign this to me before I open a PR? Thanks!
